language: clojure
lein: lein2
jdk:
- oraclejdk8
install: true
script:
- curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
- chmod a+x lein
- lein test
- bash .travis/deploy.sh
env:
  global:
  - secure: PydbH8RtuGuwbOweMv/j6FpGskw9DoMzKagRxkXSRo9sD9srOIlPhMQGnYbOistDt6zbIdwzSnjsKq8jGp2/9aKs3SCCNOd+6lRGIIukQghxOV7tYNxVI0xD54YXOc6JlexdIkxKLB7sSo4EO0Ca5UBY+UrIQ4fRCQ89UMXxz/sA/g1ypYLPnXEmmLUgfHgDCxX9PCxDVJPVfUMRvqxE0k0ujhyywJrRY06oHjgb2SRWAYzEnVJRTp53wIsD3PIYhg4ESwdwoZVuvnFq5wPCRODFe9DAuQ9TZOVnO833SE7l2JX6CNGoCs5cZSdwiR0rLVQOuT7NSM6mNZblRDhL9tSmhemjQ/QPkjU9sJ6rVM3N0WOE7XFnkrz/5vFSKjNLgnSmloC6+eRA5qU9hiNw7eAyyKS/YtNQRE9k19uP8c3CjMuwCWX20ROU9jNcvPeFlhlVerZtF6pEZFNPUIGo7t4QH6ipMB1k3jwmflhNrqLtla0Esj+apNjTSIWRTP6fsBW8bUbaYVKOs42drYDbTaFbTWdJo8e2VC2sF5u6G22BIKnJLrNO+Sv70jpG1XHXncNkXgS4jj/u2BXMSjNs/TR7ii211xyfVjF/PliOi2agSHe52M9dkmW6hmv8u6QXpw9nW2+IEBViM06KtLigUCqb/jy7D/99gKzmpSdYIaA=
  - secure: rmfSp6NhsmidN6jLrokmRQOkDcfWrJ6qG1oiHhxAZE4IPSpgJkY4t/5kXkL5io28mzGRtzRzU01fTj2RkQkAzf1Zagsklycu68T8S++WGJEnRjRUJ9aG0uYcCNITWF7us/Nl0NxtW2Ut/V+X9cqkFdeU0tRDP3YV/BZlKAhsjimW3xxalWK+4+YlT6zo8qYXC0lxRAeDT3d2LGwZ9uzcgfPCl6MwYcYdSIMh9YOQQ2LKR75IAU8LvOcX9eO6asUiNpl6qy9pMARPkWdI+yaTbeZv1U2M+o5rFa9d7vc5QtToLowM4v243hIdfLqYT17ll7gCQG3z/2OSGw5uZTQEhIi5WDJnv8wCz5nJJR1uMO862eoZIqB37epjZGLUwWBSmTluSxz/1tEjHOo8k8OkzoSouCRdMec6Au+o/Lj7PZcX6OgAQi4WB12jIig2VrMlVi26glgKP+Xo2ABP6A5EovmTALUt3l2iWbNPYp8e1Vv9aNMm1NC2w78r/2g71n4o2ApRTmNUM5dKLAMLaoMO830DqwkkYIEUVsYeQgPCRx6cq/gEaLSfK1xKtpZkFuJkAPzGL0NNK6/kcBYHTsNAiFqIN4P7GQW1nuVQTFQfPA7IcoS3XE+ciGG8EW4eJ63aymY2I/UVh+nKUAU+71z4m1cLmsaPXjY1UIXYQZPmENw=
